adding Project function and update projects_controller
WebAhead-cs2/caps-look-api pull request #33
Opened 2023-02-08 12:54 UTC by LeenMass

2023-02-08 14:50 UTC, MuhammadAw90 submitted a review, later dismissed

2023-02-08 14:50 UTC, LeenMass commented
all the comments resolved
@tawfiknasser please re-review

2023-02-08 14:51 UTC, MuhammadAw90 commented
activating prettier wasn't that complicated.
Looks great!

2023-02-08 15:06 UTC, Karyum submitted a review, later dismissed

2023-02-08 15:12 UTC, MuhammadAw90 commented
merging the previous branch caused conflict here, We're gonna fix them and request to merge again

2023-02-08 15:21 UTC, MuhammadAw90 commented
The conflict fixed !

2023-02-08 15:21 UTC, MuhammadAw90 approved these changes, later dismissed

2023-02-08 18:59 UTC, tawfiknasser commented on controllers/projects.controller.js
> +const AddingProject = catchAsync(async (req, res) => {
aren't all controllers names camelCase ?

2023-02-08 19:00 UTC, tawfiknasser requested changes
use cameCase

2023-02-09 20:28 UTC, MuhammadAw90 approved these changes

2023-02-09 21:54 UTC, Karyum approved these changes

2023-02-09 21:57 UTC, tawfiknasser approved these changes

2023-02-09 21:57 UTC, merged