Edit_Project_Put_Method
WebAhead-cs2/caps-look-api pull request #38
Opened 2023-02-09 20:19 UTC by LeenMass

2023-02-09 21:49 UTC, MuhammadAw90 submitted a review, later dismissed

2023-02-09 21:53 UTC, tawfiknasser requested changes
@LeenMass can you apply this minor change on the logger? overall you did great job!

2023-02-09 21:53 UTC, tawfiknasser commented on controllers/projects.controller.js
> +  console.log(data)
can you delete console.log and use @Astbrqeg  logger module where needed?

2023-02-09 22:12 UTC, Karyum submitted a review, later dismissed

2023-02-10 16:49 UTC, saherhanif approved these changes, later dismissed

2023-02-10 17:20 UTC, saherhanif submitted a review, later dismissed

2023-02-10 19:17 UTC, MuhammadAw90 approved these changes

2023-02-10 19:17 UTC, MuhammadAw90 commented on router.js
@Karyum , 
why the roles of SM ,RM, PM appear here in router ? (we pulled this from the main branch)

2023-02-10 19:24 UTC, tawfiknasser approved these changes

2023-02-10 19:27 UTC, merged