implement employee page BK
WebAhead-cs2/caps-look-api pull request #76
Opened 2023-02-18 23:04 UTC by LeenMass

2023-02-18 23:08 UTC, saherhanif approved these changes, later dismissed

2023-02-19 06:39 UTC, tawfiknasser requested changes

2023-02-19 06:39 UTC, tawfiknasser commented on database/init.sql
> +  project_id INTEGER REFERENCES project(id) default null,
Isn't init.sql untouchable?  Why not creating a new migration?

2023-02-23 18:06 UTC, saherhanif approved these changes, later dismissed
good job !

2023-02-23 18:12 UTC, tawfiknasser submitted a review, later dismissed

2023-02-23 18:56 UTC, merged